branch-defaults:
  default:
    environment: nutri-flask-env5
environment-defaults:
  nutri-flask-env5:
    branch: null
    repository: null
global:
  application_name: nutri-model
  default_ec2_keyname: nutri-eb
  default_platform: Python 3.9 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
